import Head from 'next/head'
import Btn from '@/components/Btn'

const MyPage = () => { 
  return (
    <>
      <Head>
        <title>MyPage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Btn text='btn text' col='red' bg='blue' /> 
    </>
  )
}

export default MyPage